name: Test & Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install backend dependencies
        working-directory: ./apps/backend
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Test frontend
        run: pnpm --filter frontend test --run

      - name: Lint frontend
        run: pnpm --filter frontend lint

      - name: Test backend
        working-directory: ./apps/backend
        run: |
          source venv/bin/activate
          PYTHONPATH=. pytest tests/ -v

      - name: Lint backend
        working-directory: ./apps/backend
        run: |
          source venv/bin/activate
          black --check app/
          isort --check app/
          flake8 app/